### ISSUE TITLE
View Current User's Posts [3]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-rubber-ducks#17]
Given the logged in user wants to view a list of posts they have created
When they select the "My Posts" link from the navbar
Then they should be taken to `/my-posts` that only shows posts they have authored
And there should be (non-functional) buttons to edit or delete each post

**Comment by DannyGambino** [comment]
CLIENT
1. add  My Posts link to NavBar
2. My Posts link navigates to /myposts. Route path "/myposts"
3. return posts 
4. add non-functional "edit" and "delete" buttons

SERVER
1. create Post class (self, id, user_id, category_id, title, publication_date, image_url, content, approved)
2. create get_my_posts function
5. create SQL statement within get_my_posts() that SELECT * FROM Posts table if user_id = post[user_id]
6. import into __init__ packages and do_Get method
