### ISSUE TITLE
Create a Tag [5]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-rubber-ducks#19]
Given a user is on the tag list page, there should be a create form on the right side of the page
When they fill out the form and submit
Then the tag should be added
And the tag list should update

**Comment by DannyGambino** [comment]
CLIENT
1. create a form in JSX in tag module
2. set state for tag/settag
3. "access do_GET from server"

SERVER
1. make a create_tag method with SQL INSERT statement
2. make new_tag instance as placeholder
3. return new_tag
4. create do_POST and call new_tag
