### ISSUE TITLE
View Tag List [3]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-rubber-ducks#21]
Given a user selects the "Tag Management" from the navbar
When they are directed to `/tags`
Then they should see a list of all tags
And tags should be ordered alphabetically
And each tag should have an edit and delete button (functionality for buttons come later)

**Comment by WillJckson** [comment]
CLIENT

add Tags Management link to NavBar
Tags Manager link navigates to /tags. Route path "/tags"
return tags 
add buttons for editing and deleting, they don't have to be functional yet

SERVER

create Tag class (self, id, label)
create get_all_tag method
create SQL statement within get_all_tags() that selects: * FROM Tags and orders it alphabetically DESC
import into init packages and do_Get method
