### ISSUE TITLE
View Category List [3]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-rubber-ducks#22]
Given a user selects the "Category Management" from the navbar
When they are directed to `/categories`
Then they should see a list of all categories
And categories should be ordered alphabetically
And each category should have an edit and delete button (functionality for buttons come later)

**Comment by WillJckson** [comment]
CLIENT

add Catagory Management link to NavBar
Catagory Manager link navigates to /categories. Route path "/categories"
return categories 

SERVER

create Category class (self, id, label)
create get_all_categories function
create SQL statement within get_all_categories() that selects: * FROM Categories and orders it alphabetically DESC
import into init packages and do_Get method
