### ISSUE TITLE
View Post Details [3]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-rubber-ducks#23]
Given a user is looking at a list of posts
When they click on the post title
Then they should be directed to the post detail page
And the details should include:

- [ ] Title
- [ ] Author's name
- [ ] Category
- [ ] Publication date
- [ ] Content

**Comment by DannyGambino** [comment]
CLIENT
1. link post to postId
2. route to post details
3. return post details

SERVER
1. method for get_single_post
2. select (title, author name, category, pub date, content)
4. add to do_Get
