### ISSUE TITLE
View All Posts [3]

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-64/rare-client-rubber-ducks#24]
Given the user clicks on the "Posts" link in the navbar
When they are directed to the /posts page
Then they should see a list of all posts, with the post title, author name, and category
And the posts should be ordered by the date they were added, most recent first

**Comment by DannyGambino** [comment]
CLIENT
1. add Posts link to NavBar
2. Posts link navigates to /posts. Route path "/posts"
3. return posts ordered by date added

SERVER
1. create Post class (self, id, user_id, category_id, title, publication_date, image_url, content, approved)
2. create get_all_posts function
4. create SQL statement within get_all_posts() that selects: title, author name, and category from Posts table
5. import into __init__ packages and do_Get method
